{{- $secretName := printf "%s" .Release.Name }}
{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace  $secretName ) | default dict }}
{{- $secretData := (get $secretObj "data") | default dict }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels: {{- include "labels" . | nindent 4 }}
data:
  #-- set these below for plain Postgres, for crunchy it is handled by the operator, so needs to be dealt with differently.
  {{- if not .Values.global.crunchyEnabled }}
  POSTGRESQL_PASSWORD: {{ .Values.global.secrets.databasePassword | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.global.secrets.databasePassword | b64enc | quote }}
  POSTGRESQL_USER: {{  .Values.global.secrets.databaseUser | b64enc | quote }}
  POSTGRES_USER: {{  .Values.global.secrets.databaseUser | b64enc | quote }}
  POSTGRESQL_DATABASE: {{  .Values.global.secrets.databaseName | b64enc | quote }}
  POSTGRES_DB: {{  .Values.global.secrets.databaseName | b64enc | quote }}
  {{- end }}

