{{- $superuserPassword := (randAlphaNum 32) | b64enc | quote }}
{{- $adminPassword := (randAlphaNum 32) | b64enc | quote }}
{{- $standbyPassword := (randAlphaNum 32) | b64enc | quote }}
{{- $appuserPassword := (randAlphaNum 32) | b64enc | quote }}
{{- $secretName := print (include "spilo.fullname" .) }}

{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName ) }}
{{- if $secret }}
{{- $superuserPassword = index $secret.data "password-superuser" }}
{{- $adminPassword = index $secret.data "password-admin" }}
{{- $standbyPassword = index $secret.data "password-standby" }}
{{- $appuserPassword = index $secret.data "password-appuser" }}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "spilo.fullname" . }}
  labels: {{ include "spilo.labels" . | nindent 4 }}
type: Opaque
data:
  username-appuser: {{ .Values.credentials.appuser.username | b64enc }}
  username-superuser: {{ .Values.credentials.superuser.username | b64enc }}
  username-admin: {{ .Values.credentials.admin.username | b64enc }}
  username-standby: {{ .Values.credentials.standby.username | b64enc }}
  password-superuser: {{ $superuserPassword }}
  password-admin: {{ $adminPassword }}
  password-standby: {{ $standbyPassword }}
  password-appuser: {{ $appuserPassword }}

